// <auto-generated />
using System;
using LifetimeLiveHouse.Access.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LifetimeLiveHouse.Access.Migrations
{
    [DbContext(typeof(LifetimeLiveHouseSysDBContext))]
    partial class LifetimeLiveHouseSysDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AttendanceRecord", b =>
                {
                    b.Property<long>("AttendanceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AttendanceID"));

                    b.Property<long>("EmployeeID")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("PunchInTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PunchOutTime")
                        .HasColumnType("datetime2");

                    b.HasKey("AttendanceID");

                    b.HasIndex("EmployeeID");

                    b.ToTable("AttendanceRecord");
                });

            modelBuilder.Entity("BandRole", b =>
                {
                    b.Property<string>("BandRoleID")
                        .HasMaxLength(1)
                        .HasColumnType("nchar");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("BandRoleID");

                    b.ToTable("BandRole");
                });

            modelBuilder.Entity("Cart", b =>
                {
                    b.Property<long>("CartID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("CartID"));

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<long>("MemberID")
                        .HasColumnType("bigint");

                    b.Property<long>("ProductID")
                        .HasColumnType("bigint");

                    b.HasKey("CartID");

                    b.HasIndex("MemberID");

                    b.HasIndex("ProductID");

                    b.ToTable("Cart");
                });

            modelBuilder.Entity("Category", b =>
                {
                    b.Property<string>("CateID")
                        .HasMaxLength(5)
                        .HasColumnType("nchar");

                    b.Property<string>("CateName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("CateID");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("Coupon", b =>
                {
                    b.Property<long>("cNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("cNo"));

                    b.Property<decimal>("Discount")
                        .HasColumnType("money");

                    b.Property<long>("MemberID")
                        .HasColumnType("bigint");

                    b.Property<long>("ProductID")
                        .HasColumnType("bigint");

                    b.Property<string>("cDesc")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("cNo");

                    b.HasIndex("MemberID");

                    b.HasIndex("ProductID");

                    b.ToTable("Coupon");
                });

            modelBuilder.Entity("EmployeeAccount", b =>
                {
                    b.Property<string>("Email")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<long>("EmployeeID")
                        .HasColumnType("bigint");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Email");

                    b.HasIndex("EmployeeID")
                        .IsUnique();

                    b.ToTable("EmployeeAccount");
                });

            modelBuilder.Entity("Event", b =>
                {
                    b.Property<long>("EventID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("EventID"));

                    b.Property<string>("Discription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("EventPicture")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("MemberID")
                        .HasColumnType("bigint");

                    b.Property<decimal>("RegistrationFee")
                        .HasColumnType("money");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("StatusCode")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nchar");

                    b.Property<long>("StoreID")
                        .HasColumnType("bigint");

                    b.HasKey("EventID");

                    b.HasIndex("MemberID");

                    b.HasIndex("StatusCode");

                    b.HasIndex("StoreID");

                    b.ToTable("Event");
                });

            modelBuilder.Entity("EventStatus", b =>
                {
                    b.Property<string>("StatusCode")
                        .HasMaxLength(1)
                        .HasColumnType("nchar");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("StatusCode");

                    b.ToTable("EventStatus");
                });

            modelBuilder.Entity("Instrument", b =>
                {
                    b.Property<long>("InstrumentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("InstrumentID"));

                    b.Property<string>("Discription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InstrumentName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("InstrumentPhoto")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long?>("MemberID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("OutRentTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("RentFeePerHour")
                        .HasColumnType("money");

                    b.Property<DateTime>("RentTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("StoreID")
                        .HasColumnType("bigint");

                    b.HasKey("InstrumentID");

                    b.HasIndex("MemberID");

                    b.HasIndex("StoreID");

                    b.ToTable("Instrument");
                });

            modelBuilder.Entity("LifetimeLiveHouse.Models.Employee", b =>
                {
                    b.Property<long>("EmployeeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("EmployeeID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("RoleCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<long>("StoreID")
                        .HasColumnType("bigint");

                    b.Property<string>("Tel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("EmployeeID");

                    b.HasIndex("RoleCode");

                    b.HasIndex("StoreID");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("LifetimeLiveHouse.Models.EmployeeRole", b =>
                {
                    b.Property<string>("RoleCode")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("RoleCode");

                    b.ToTable("EmployeeRole");
                });

            modelBuilder.Entity("LifetimeLiveHouse.Models.MemberEmailVerificationStatus", b =>
                {
                    b.Property<long>("MemberID")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("EmailVerificationTokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailVerificationTokenHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("bit");

                    b.HasKey("MemberID");

                    b.ToTable("MemberEmailVerificationStatus");
                });

            modelBuilder.Entity("LifetimeLiveHouse.Models.MemberPhoneVerificationStatus", b =>
                {
                    b.Property<long>("MemberID")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsPhoneVerified")
                        .HasColumnType("bit");

                    b.HasKey("MemberID");

                    b.ToTable("MemberPhoneVerificationStatus");
                });

            modelBuilder.Entity("LifetimeLiveHouse.Models.News", b =>
                {
                    b.Property<long>("NewsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("NewsID"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewsTitle")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Picture")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PostDate")
                        .HasColumnType("datetime2");

                    b.HasKey("NewsID");

                    b.ToTable("News");
                });

            modelBuilder.Entity("LifetimeLiveHouse.Models.PasswordResetToken", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("MemberID")
                        .HasColumnType("bigint");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Used")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MemberID");

                    b.ToTable("PasswordResetToken");
                });

            modelBuilder.Entity("LifetimeLiveHouse.Models.ProductStatus", b =>
                {
                    b.Property<string>("StatusCode")
                        .HasMaxLength(1)
                        .HasColumnType("nchar");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("StatusCode");

                    b.ToTable("ProductStatus");
                });

            modelBuilder.Entity("LifetimeLiveHouse.Models.RegisteredEvent", b =>
                {
                    b.Property<long>("RecordID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RecordID"));

                    b.Property<long>("EventID")
                        .HasColumnType("bigint");

                    b.Property<long>("MemberID")
                        .HasColumnType("bigint");

                    b.HasKey("RecordID");

                    b.HasIndex("EventID");

                    b.HasIndex("MemberID");

                    b.ToTable("RegisteredEvent");
                });

            modelBuilder.Entity("LifetimeLiveHouse.Models.Store", b =>
                {
                    b.Property<long>("StoreID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("StoreID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Discription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("RentFeePerHour")
                        .HasColumnType("money");

                    b.Property<string>("StoreName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("sTel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("StoreID");

                    b.ToTable("Store");
                });

            modelBuilder.Entity("Live", b =>
                {
                    b.Property<long>("LiveID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("LiveID"));

                    b.Property<decimal>("Admission")
                        .HasColumnType("money");

                    b.Property<string>("BandRoleID")
                        .IsRequired()
                        .HasColumnType("nchar(1)");

                    b.Property<string>("Discription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("EventStatusStatusCode")
                        .HasColumnType("nchar(1)");

                    b.Property<string>("LiveName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("LiveSong")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<long>("MemberID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("StatusCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("StoreID")
                        .HasColumnType("bigint");

                    b.HasKey("LiveID");

                    b.HasIndex("BandRoleID");

                    b.HasIndex("EventStatusStatusCode");

                    b.HasIndex("MemberID");

                    b.HasIndex("StoreID");

                    b.ToTable("Live");
                });

            modelBuilder.Entity("LoginRecord", b =>
                {
                    b.Property<long>("RecordID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RecordID"));

                    b.Property<long>("ContinuousLoginDate")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("LoginDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("MemberID")
                        .HasColumnType("bigint");

                    b.Property<string>("Record")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("RecordID");

                    b.HasIndex("MemberID");

                    b.ToTable("LoginRecord");
                });

            modelBuilder.Entity("Member", b =>
                {
                    b.Property<long>("MemberID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MemberID"));

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Cash")
                        .HasColumnType("money");

                    b.Property<string>("CellphoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("MemberPoint")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("StatusCode")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nchar");

                    b.HasKey("MemberID");

                    b.HasIndex("StatusCode");

                    b.ToTable("Member");
                });

            modelBuilder.Entity("MemberAccount", b =>
                {
                    b.Property<string>("Email")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<long>("MemberID")
                        .HasColumnType("bigint");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Email");

                    b.HasIndex("MemberID");

                    b.ToTable("MemberAccount");
                });

            modelBuilder.Entity("MemberHeadPicture", b =>
                {
                    b.Property<string>("Picture")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("MemberID")
                        .HasColumnType("bigint");

                    b.HasKey("Picture");

                    b.HasIndex("MemberID")
                        .IsUnique();

                    b.ToTable("MemberHeadPicture");
                });

            modelBuilder.Entity("MemberPicture", b =>
                {
                    b.Property<string>("Picture")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("MemberID")
                        .HasColumnType("bigint");

                    b.HasKey("Picture");

                    b.HasIndex("MemberID");

                    b.ToTable("MemberPicture");
                });

            modelBuilder.Entity("MemberStatus", b =>
                {
                    b.Property<string>("StatusCode")
                        .HasMaxLength(1)
                        .HasColumnType("nchar");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("StatusCode");

                    b.ToTable("MemberStatus");
                });

            modelBuilder.Entity("Notification", b =>
                {
                    b.Property<long>("NotificationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("NotificationID"));

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<long>("MemberID")
                        .HasColumnType("bigint");

                    b.Property<bool>("Readed")
                        .HasColumnType("bit");

                    b.HasKey("NotificationID");

                    b.HasIndex("MemberID");

                    b.ToTable("Notification");
                });

            modelBuilder.Entity("Order", b =>
                {
                    b.Property<long>("OrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("OrderID"));

                    b.Property<long?>("EmployeeID")
                        .HasColumnType("bigint");

                    b.Property<long>("MemberID")
                        .HasColumnType("bigint");

                    b.Property<string>("Note")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PayCode")
                        .HasMaxLength(2)
                        .HasColumnType("nchar(2)");

                    b.Property<string>("StatusCode")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("oTel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("OrderID");

                    b.HasIndex("EmployeeID");

                    b.HasIndex("MemberID");

                    b.HasIndex("PayCode");

                    b.HasIndex("StatusCode");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("OrderDetail", b =>
                {
                    b.Property<long>("OrderID")
                        .HasColumnType("bigint");

                    b.Property<long>("ProductID")
                        .HasColumnType("bigint");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("money");

                    b.Property<string>("ShippingAddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ShippingMethodCode")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nchar");

                    b.HasKey("OrderID", "ProductID");

                    b.HasIndex("ShippingMethodCode");

                    b.ToTable("OrderDetail");
                });

            modelBuilder.Entity("OrderDetailProduct", b =>
                {
                    b.Property<long>("ProductsProductID")
                        .HasColumnType("bigint");

                    b.Property<long>("OrderDetailOrderID")
                        .HasColumnType("bigint");

                    b.Property<long>("OrderDetailProductID")
                        .HasColumnType("bigint");

                    b.HasKey("ProductsProductID", "OrderDetailOrderID", "OrderDetailProductID");

                    b.HasIndex("OrderDetailOrderID", "OrderDetailProductID");

                    b.ToTable("OrderDetailProduct");
                });

            modelBuilder.Entity("OrderOrderDetail", b =>
                {
                    b.Property<long>("OrdersOrderID")
                        .HasColumnType("bigint");

                    b.Property<long>("OrderDetailOrderID")
                        .HasColumnType("bigint");

                    b.Property<long>("OrderDetailProductID")
                        .HasColumnType("bigint");

                    b.HasKey("OrdersOrderID", "OrderDetailOrderID", "OrderDetailProductID");

                    b.HasIndex("OrderDetailOrderID", "OrderDetailProductID");

                    b.ToTable("OrderOrderDetail");
                });

            modelBuilder.Entity("OrderStatus", b =>
                {
                    b.Property<string>("StatusCode")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("StatusCode");

                    b.ToTable("OrderStatus");
                });

            modelBuilder.Entity("PayType", b =>
                {
                    b.Property<string>("PayCode")
                        .HasMaxLength(2)
                        .HasColumnType("nchar");

                    b.Property<decimal>("ShippingFee")
                        .HasColumnType("money");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("PayCode");

                    b.ToTable("PayType");
                });

            modelBuilder.Entity("Product", b =>
                {
                    b.Property<long>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ProductID"));

                    b.Property<string>("CateID")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nchar");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Photo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Pricing")
                        .HasColumnType("money");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<long>("ProductNum")
                        .HasColumnType("bigint");

                    b.Property<decimal>("RetailPrice")
                        .HasColumnType("money");

                    b.Property<string>("StatusCode")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nchar");

                    b.HasKey("ProductID");

                    b.HasIndex("CateID");

                    b.HasIndex("StatusCode");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("RehearsalStudio", b =>
                {
                    b.Property<long>("RehearsalStudioID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RehearsalStudioID"));

                    b.Property<string>("Discription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("MemberID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("OutRentTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("RehearsalStudioName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("RehearsalStudioPhoto")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("RentFeePerHour")
                        .HasColumnType("money");

                    b.Property<DateTime>("StartRentTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("StoreID")
                        .HasColumnType("bigint");

                    b.HasKey("RehearsalStudioID");

                    b.HasIndex("MemberID");

                    b.HasIndex("StoreID");

                    b.ToTable("RehearsalStudio");
                });

            modelBuilder.Entity("Seat", b =>
                {
                    b.Property<long>("SeatID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SeatID"));

                    b.Property<long>("MemberID")
                        .HasColumnType("bigint");

                    b.Property<long>("StoreID")
                        .HasColumnType("bigint");

                    b.HasKey("SeatID");

                    b.HasIndex("MemberID")
                        .IsUnique();

                    b.HasIndex("StoreID");

                    b.ToTable("Seat");
                });

            modelBuilder.Entity("ShippingMethod", b =>
                {
                    b.Property<string>("ShippingMethodCode")
                        .HasMaxLength(1)
                        .HasColumnType("nchar");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("ShippingMethodCode");

                    b.ToTable("ShippingMethod");
                });

            modelBuilder.Entity("AttendanceRecord", b =>
                {
                    b.HasOne("LifetimeLiveHouse.Models.Employee", "Employee")
                        .WithMany("AttendanceRecords")
                        .HasForeignKey("EmployeeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Cart", b =>
                {
                    b.HasOne("Member", "Member")
                        .WithMany("Carts")
                        .HasForeignKey("MemberID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Coupon", b =>
                {
                    b.HasOne("Member", "Member")
                        .WithMany("Coupons")
                        .HasForeignKey("MemberID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Product", "Product")
                        .WithMany("Coupons")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("EmployeeAccount", b =>
                {
                    b.HasOne("LifetimeLiveHouse.Models.Employee", "Employee")
                        .WithOne("EmployeeAccount")
                        .HasForeignKey("EmployeeAccount", "EmployeeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Event", b =>
                {
                    b.HasOne("Member", "Member")
                        .WithMany("Events")
                        .HasForeignKey("MemberID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EventStatus", "EventStatus")
                        .WithMany("Events")
                        .HasForeignKey("StatusCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LifetimeLiveHouse.Models.Store", "Store")
                        .WithMany("Events")
                        .HasForeignKey("StoreID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EventStatus");

                    b.Navigation("Member");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("Instrument", b =>
                {
                    b.HasOne("Member", "Member")
                        .WithMany("Instruments")
                        .HasForeignKey("MemberID");

                    b.HasOne("LifetimeLiveHouse.Models.Store", "Store")
                        .WithMany("Instruments")
                        .HasForeignKey("StoreID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("LifetimeLiveHouse.Models.Employee", b =>
                {
                    b.HasOne("LifetimeLiveHouse.Models.EmployeeRole", "EmployeeRole")
                        .WithMany("Employees")
                        .HasForeignKey("RoleCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LifetimeLiveHouse.Models.Store", "Store")
                        .WithMany("Employees")
                        .HasForeignKey("StoreID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmployeeRole");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("LifetimeLiveHouse.Models.MemberEmailVerificationStatus", b =>
                {
                    b.HasOne("Member", "Member")
                        .WithOne("MemberEmailVerificationStatus")
                        .HasForeignKey("LifetimeLiveHouse.Models.MemberEmailVerificationStatus", "MemberID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("LifetimeLiveHouse.Models.MemberPhoneVerificationStatus", b =>
                {
                    b.HasOne("Member", "Member")
                        .WithOne("MemberPhoneVerificationStatus")
                        .HasForeignKey("LifetimeLiveHouse.Models.MemberPhoneVerificationStatus", "MemberID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("LifetimeLiveHouse.Models.PasswordResetToken", b =>
                {
                    b.HasOne("Member", "Member")
                        .WithMany("PasswordResetTokens")
                        .HasForeignKey("MemberID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("LifetimeLiveHouse.Models.RegisteredEvent", b =>
                {
                    b.HasOne("Event", "Event")
                        .WithMany("RegisteredEvents")
                        .HasForeignKey("EventID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Member", "Member")
                        .WithMany("RegisteredEvents")
                        .HasForeignKey("MemberID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("Live", b =>
                {
                    b.HasOne("BandRole", "BandRole")
                        .WithMany("Lives")
                        .HasForeignKey("BandRoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventStatus", "EventStatus")
                        .WithMany()
                        .HasForeignKey("EventStatusStatusCode");

                    b.HasOne("Member", "Member")
                        .WithMany("Lives")
                        .HasForeignKey("MemberID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LifetimeLiveHouse.Models.Store", "Store")
                        .WithMany("Lives")
                        .HasForeignKey("StoreID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BandRole");

                    b.Navigation("EventStatus");

                    b.Navigation("Member");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("LoginRecord", b =>
                {
                    b.HasOne("Member", "Member")
                        .WithMany("LoginRecords")
                        .HasForeignKey("MemberID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("Member", b =>
                {
                    b.HasOne("MemberStatus", "MemberStatus")
                        .WithMany("Members")
                        .HasForeignKey("StatusCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MemberStatus");
                });

            modelBuilder.Entity("MemberAccount", b =>
                {
                    b.HasOne("Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("MemberHeadPicture", b =>
                {
                    b.HasOne("Member", "Member")
                        .WithOne("MemberHeadPicture")
                        .HasForeignKey("MemberHeadPicture", "MemberID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("MemberPicture", b =>
                {
                    b.HasOne("Member", "Member")
                        .WithMany("MemberPictures")
                        .HasForeignKey("MemberID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("Notification", b =>
                {
                    b.HasOne("Member", "Member")
                        .WithMany("Notifications")
                        .HasForeignKey("MemberID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("Order", b =>
                {
                    b.HasOne("LifetimeLiveHouse.Models.Employee", "Employee")
                        .WithMany("Orders")
                        .HasForeignKey("EmployeeID");

                    b.HasOne("Member", "Member")
                        .WithMany("Orders")
                        .HasForeignKey("MemberID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PayType", "PayType")
                        .WithMany("Orders")
                        .HasForeignKey("PayCode");

                    b.HasOne("OrderStatus", "OrderStatus")
                        .WithMany("Orders")
                        .HasForeignKey("StatusCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Member");

                    b.Navigation("OrderStatus");

                    b.Navigation("PayType");
                });

            modelBuilder.Entity("OrderDetail", b =>
                {
                    b.HasOne("ShippingMethod", "ShippingMethod")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ShippingMethodCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShippingMethod");
                });

            modelBuilder.Entity("OrderDetailProduct", b =>
                {
                    b.HasOne("Product", null)
                        .WithMany()
                        .HasForeignKey("ProductsProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OrderDetail", null)
                        .WithMany()
                        .HasForeignKey("OrderDetailOrderID", "OrderDetailProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OrderOrderDetail", b =>
                {
                    b.HasOne("Order", null)
                        .WithMany()
                        .HasForeignKey("OrdersOrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OrderDetail", null)
                        .WithMany()
                        .HasForeignKey("OrderDetailOrderID", "OrderDetailProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Product", b =>
                {
                    b.HasOne("Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CateID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LifetimeLiveHouse.Models.ProductStatus", "ProductStatus")
                        .WithMany("Products")
                        .HasForeignKey("StatusCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("ProductStatus");
                });

            modelBuilder.Entity("RehearsalStudio", b =>
                {
                    b.HasOne("Member", "Member")
                        .WithMany("RehearsalStudios")
                        .HasForeignKey("MemberID");

                    b.HasOne("LifetimeLiveHouse.Models.Store", "Store")
                        .WithMany("RehearsalStudios")
                        .HasForeignKey("StoreID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("Seat", b =>
                {
                    b.HasOne("Member", "Member")
                        .WithOne("Seat")
                        .HasForeignKey("Seat", "MemberID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LifetimeLiveHouse.Models.Store", "Store")
                        .WithMany("Seats")
                        .HasForeignKey("StoreID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("BandRole", b =>
                {
                    b.Navigation("Lives");
                });

            modelBuilder.Entity("Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Event", b =>
                {
                    b.Navigation("RegisteredEvents");
                });

            modelBuilder.Entity("EventStatus", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("LifetimeLiveHouse.Models.Employee", b =>
                {
                    b.Navigation("AttendanceRecords");

                    b.Navigation("EmployeeAccount")
                        .IsRequired();

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("LifetimeLiveHouse.Models.EmployeeRole", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("LifetimeLiveHouse.Models.ProductStatus", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("LifetimeLiveHouse.Models.Store", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("Events");

                    b.Navigation("Instruments");

                    b.Navigation("Lives");

                    b.Navigation("RehearsalStudios");

                    b.Navigation("Seats");
                });

            modelBuilder.Entity("Member", b =>
                {
                    b.Navigation("Carts");

                    b.Navigation("Coupons");

                    b.Navigation("Events");

                    b.Navigation("Instruments");

                    b.Navigation("Lives");

                    b.Navigation("LoginRecords");

                    b.Navigation("MemberEmailVerificationStatus")
                        .IsRequired();

                    b.Navigation("MemberHeadPicture");

                    b.Navigation("MemberPhoneVerificationStatus")
                        .IsRequired();

                    b.Navigation("MemberPictures");

                    b.Navigation("Notifications");

                    b.Navigation("Orders");

                    b.Navigation("PasswordResetTokens");

                    b.Navigation("RegisteredEvents");

                    b.Navigation("RehearsalStudios");

                    b.Navigation("Seat");
                });

            modelBuilder.Entity("MemberStatus", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("OrderStatus", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("PayType", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Product", b =>
                {
                    b.Navigation("Coupons");
                });

            modelBuilder.Entity("ShippingMethod", b =>
                {
                    b.Navigation("OrderDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
