<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.2.0" />
    <PackageReference Include="Google.Apis.Auth" Version="1.75.0" />
    <PackageReference Include="MailKit" Version="4.17.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\HatsuneMIkuShop.Models\LifetimeLiveHouse.Models.csproj" />
  </ItemGroup>

</Project>
