// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LifetimeLiveHouse.Models;

public partial class AttendanceRecord
{
    public long AttendanceID { get; set; }

    public DateTime? PunchInTime { get; set; }

    public DateTime? PunchOutTime { get; set; }

    public long EmployeeID { get; set; }

    public virtual Employee Employee { get; set; }
}