// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LifetimeLiveHouse.Models;

public partial class BandRole
{
    public string BandRoleID { get; set; }

    public string Role { get; set; }

    public virtual ICollection<Live> Live { get; set; } = new List<Live>();
}