// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LifetimeLiveHouse.Models;

public partial class Cart
{
    public long CartID { get; set; }

    public long ProductID { get; set; }

    public long MemberID { get; set; }

    public int Count { get; set; }

    public virtual Member Member { get; set; }

    public virtual Product Product { get; set; }
}