// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LifetimeLiveHouse.Models;

public partial class Employee
{
    public long EmployeeID { get; set; }

    public string Name { get; set; }

    public DateTime HireDate { get; set; }

    public string Address { get; set; }

    public DateTime Birthday { get; set; }

    public string Tel { get; set; }

    public string RoleCode { get; set; }

    public long StoreID { get; set; }

    public virtual ICollection<AttendanceRecord> AttendanceRecord { get; set; } = new List<AttendanceRecord>();

    public virtual EmployeeAccount EmployeeAccount { get; set; }

    public virtual ICollection<Order> Order { get; set; } = new List<Order>();

    public virtual EmployeeRole RoleCodeNavigation { get; set; }

    public virtual Store Store { get; set; }
}