// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LifetimeLiveHouse.Models;

public partial class EmployeeRole
{
    public string RoleCode { get; set; }

    public string RoleName { get; set; }

    public virtual ICollection<Employee> Employee { get; set; } = new List<Employee>();
}