// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LifetimeLiveHouse.Models;

public partial class Event
{
    public long EventID { get; set; }

    public string EventName { get; set; }

    public DateTime StartTime { get; set; }

    public DateTime EndTime { get; set; }

    public decimal RegistrationFee { get; set; }

    public string Discription { get; set; }

    public string EventPicture { get; set; }

    public long StoreID { get; set; }

    public long MemberID { get; set; }

    public string StatusCode { get; set; }

    public virtual Member Member { get; set; }

    public virtual ICollection<RegisteredEvent> RegisteredEvent { get; set; } = new List<RegisteredEvent>();

    public virtual EventStatus StatusCodeNavigation { get; set; }

    public virtual Store Store { get; set; }
}