// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LifetimeLiveHouse.Models;

public partial class EventStatus
{
    public string StatusCode { get; set; }

    public string Status { get; set; }

    public virtual ICollection<Event> Event { get; set; } = new List<Event>();

    public virtual ICollection<Live> Live { get; set; } = new List<Live>();
}