// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LifetimeLiveHouse.Models;

public partial class Live
{
    public long LiveID { get; set; }

    public string LiveName { get; set; }

    public DateTime StartTime { get; set; }

    public DateTime EndTime { get; set; }

    public decimal Admission { get; set; }

    public string Discription { get; set; }

    public string LiveSong { get; set; }

    public string BandRoleID { get; set; }

    public long StoreID { get; set; }

    public long MemberID { get; set; }

    public string StatusCode { get; set; }

    public string EventStatusStatusCode { get; set; }

    public virtual BandRole BandRole { get; set; }

    public virtual EventStatus EventStatusStatusCodeNavigation { get; set; }

    public virtual Member Member { get; set; }

    public virtual Store Store { get; set; }
}