// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LifetimeLiveHouse.Models;

public partial class LoginRecord
{
    public long RecordID { get; set; }

    public string Record { get; set; }

    public DateTime LoginDate { get; set; }

    public long ContinuousLoginDate { get; set; }

    public long MemberID { get; set; }

    public virtual Member Member { get; set; }
}