// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LifetimeLiveHouse.Models;

public partial class MemberStatus
{
    public string StatusCode { get; set; }

    public string Status { get; set; }

    public virtual ICollection<Member> Member { get; set; } = new List<Member>();
}