// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LifetimeLiveHouse.Models;

public partial class MemberAccount
{
    public string Email { get; set; }

    public string Password { get; set; }

    public long MemberID { get; set; }

    public virtual Member Member { get; set; }
}