// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LifetimeLiveHouse.Models;

public partial class MemberEmailVerificationStatus
{
    public long MemberID { get; set; }

    public bool IsEmailVerified { get; set; }

    public string EmailVerificationTokenHash { get; set; }

    public DateTime? EmailVerificationTokenExpiry { get; set; }

    public virtual Member Member { get; set; }
}