// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LifetimeLiveHouse.Models;

public partial class News
{
    public long NewsID { get; set; }

    public string NewsTitle { get; set; }

    public string Author { get; set; }

    public string Description { get; set; }

    public string Picture { get; set; }

    public DateTime PostDate { get; set; }
}