// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LifetimeLiveHouse.Models;

public partial class Notification
{
    public long NotificationID { get; set; }

    public string Description { get; set; }

    public bool Readed { get; set; }

    public long MemberID { get; set; }

    public virtual Member Member { get; set; }
}