// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LifetimeLiveHouse.Models;

public partial class PasswordResetToken
{
    public long Id { get; set; }

    public long MemberID { get; set; }

    public string TokenHash { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime ExpiresAt { get; set; }

    public bool Used { get; set; }

    public DateTime? UsedAt { get; set; }

    public virtual Member Member { get; set; }
}