// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LifetimeLiveHouse.Models;

public partial class PayType
{
    public string PayCode { get; set; }

    public string Type { get; set; }

    public decimal ShippingFee { get; set; }

    public virtual ICollection<Order> Order { get; set; } = new List<Order>();
}