// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LifetimeLiveHouse.Models;

public partial class ProductStatus
{
    public string StatusCode { get; set; }

    public string Status { get; set; }

    public virtual ICollection<Product> Product { get; set; } = new List<Product>();
}