// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LifetimeLiveHouse.Models;

public partial class Product
{
    public long ProductID { get; set; }

    public string StatusCode { get; set; }

    public string ProductName { get; set; }

    public long ProductNum { get; set; }

    public decimal Pricing { get; set; }

    public decimal RetailPrice { get; set; }

    public string Description { get; set; }

    public string Photo { get; set; }

    public DateTime CreatedDate { get; set; }

    public string CateID { get; set; }

    public long Inventory { get; set; }

    public virtual ICollection<Cart> Cart { get; set; } = new List<Cart>();

    public virtual Category Cate { get; set; }

    public virtual ICollection<Coupon> Coupon { get; set; } = new List<Coupon>();

    public virtual ProductStatus StatusCodeNavigation { get; set; }

    public virtual ICollection<OrderDetail> OrderDetail { get; set; } = new List<OrderDetail>();
}