// <auto-generated />
using System;
using HatsuneMikuShopAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HatsuneMikuShopAPI.Migrations
{
    [DbContext(typeof(MikuMusicShopContext))]
<<<<<<<< HEAD:HatsuneMikuShopAPI/HatsuneMikuShopAPI/Migrations/20250718035011_重建資料表.Designer.cs
<<<<<<<< HEAD:HatsuneMikuShopAPI/HatsuneMikuShopAPI/Migrations/20250718035011_重建資料表.Designer.cs
========
>>>>>>>> abfe7156f0424137ca89cb0a14e9dcaa344ae50c:HatsuneMikuShopAPI/Migrations/20250718081109_重建資料庫.Designer.cs
<<<<<<<< Updated upstream:HatsuneMikuShopAPI/HatsuneMikuShopAPI/Migrations/20250718035011_重建資料表.Designer.cs
    [Migration("20250718035011_重建資料表")]
    partial class 重建資料表
========
    [Migration("20250718081109_重建資料庫")]
    partial class 重建資料庫
>>>>>>>> Stashed changes:HatsuneMikuShopAPI/Migrations/20250718081109_重建資料庫.Designer.cs
<<<<<<<< HEAD:HatsuneMikuShopAPI/HatsuneMikuShopAPI/Migrations/20250718035011_重建資料表.Designer.cs
========
    partial class MikuMusicShopContextModelSnapshot : ModelSnapshot
>>>>>>>> abfe7156f0424137ca89cb0a14e9dcaa344ae50c:HatsuneMikuShopAPI/Migrations/MikuMusicShopContextModelSnapshot.cs
========
>>>>>>>> abfe7156f0424137ca89cb0a14e9dcaa344ae50c:HatsuneMikuShopAPI/Migrations/20250718081109_重建資料庫.Designer.cs
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HatsuneMikuShopAPI.Models.Coupon", b =>
                {
                    b.Property<int>("CouponId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CouponId"));

                    b.HasKey("CouponId");

                    b.ToTable("Coupon");
                });

            modelBuilder.Entity("HatsuneMikuShopAPI.Models.DeliveryBoy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Store_Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DeliveryBoy");
                });

            modelBuilder.Entity("HatsuneMikuShopAPI.Models.HeadPicture", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("headPictureFileName")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.HasKey("UserId", "headPictureFileName");

                    b.ToTable("HeadPicture");
                });

            modelBuilder.Entity("HatsuneMikuShopAPI.Models.OrderForm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("OrderTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("PaymentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("OrderForm");
                });

            modelBuilder.Entity("HatsuneMikuShopAPI.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhotoName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("HatsuneMikuShopAPI.Models.Store", b =>
                {
                    b.Property<int>("Store_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Store_Id"));

                    b.HasKey("Store_Id");

                    b.ToTable("Store");
                });

            modelBuilder.Entity("HatsuneMikuShopAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("MikuMikuPoint")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(2147483647)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("Sex")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Email" }, "IX_User_Email")
                        .IsUnique();

                    b.HasIndex(new[] { "Name" }, "IX_User_Name");

                    b.HasIndex(new[] { "PhoneNumber" }, "IX_User_PhoneNumber")
                        .IsUnique();

                    b.ToTable("User");
                });
#pragma warning restore 612, 618
        }
    }
}
